sudo: required

language: python
  - 3.6

services:
  - docker

env:
  global:
    - DOCKER_USER="thenomemac" # DOCKER_USER
    - secure: "eua4yMd9g9hemu58/SKSXS9NqZ8VM6G76G9d+RHzCINhE6DPRefG35FmCzTwcp1FrUui0t6/dUKPXZZ1+iKrZWzyK48EW5EOiMz/6wlHksQ2B+t27BvGoNrnUZyhlUvkJK0bUalMcl4OrvMQHMAoMNmU5uZLv3W1AV2xAzESSPLNGb1cz1QQj8jMVXveEUMQKYoTqP/XqbGXSM0QH1eVAs7kjjXGW1G512dULeSCmNZf3XEjIVS9nZJC4ywfVtYs0pEF0JdyHYFk/+zgx8DRDzhVVz4f6/0TT06BqjYXeKXdJxqRPQbMtGycEsr5aB4HLZWXTNinzWGO5leYOVYtSMK3n0NPCl1EHPxqysi3B9wDeb1GGKEhKWrcjN315zCsfqOMeTtCp/yftvAccRx3gL5AY8c8PRQwQPTDLoczjMIuM4hdHWFgoImk4QpzgkmHA5Vw6p3aWULmWKbftjtQr6ZFEmDWFTZYI4bewQBJ3VK2QuhG0Q+ieK4FG7J6BGCrT4KLxWaF75yqjOzubgr+J1rjBFY4CCu2M61yTC1gSc19l4vevU7FVGFke93lLiua4/h1W38lX4gCJzgsiDAq6RfKDFS45hyXRPex1oSnrbCq42f+kAzOF8C5JCFrQ/tZIuyV8gddbgXWdoFt37kAe4OHz+X2ybtvBGrfV/Hoi1o=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO="thenomemac/fishapp"

before_install:
  - docker --version
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo "$REPO:$COMMIT $REPO:$TAG"
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - echo "$REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER"
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker run -d -p 127.0.0.1:8000:8000 $REPO /bin/bash -c "echo 'build done'";
  - docker ps -a

script:
  - echo 'hello testing world'

after_success:
  - echo 'after so much success'
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO
